---
##@ref https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#variables-and-vaults
ansible_ssh_user: "ubuntu"
current_user: "ubuntu"
server_name: "pm4server"

repo_git_url: "https://github.com/turnikk/pm4core-docker/"
ansible_ssh_private_key_file: "~/.ssh/ubuntu_oci_deloitte"
app_work_dir: /var/dockers/{{ app_name }}/

# Docker Compose options.
docker_install_compose: true
docker_compose_version: "1.28.6"
docker_compose_url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
docker_compose_path: /usr/local/bin/docker-compose

#other config
cache_driver: file
session_driver: file
app_env: production
app_debug: false
app_key: "your_app_key"
app_name: "pm4neom"
app_url: "/"
