---
- hosts: oci
  sudo: yes
  gather_facts: no

  vars_files:
    - ./group_vars/vars.yml
  roles:
    - misc
#    - mysql
    - nginx
    - bootstrap-app
    - code-deploy
    ###
  handlers:
    - include: handlers/main.yml
#
#just for sake of !!
#- name: Set date.timezone for FPM
#  lineinfile:
#    dest: /etc/php/{{php_version}}/fpm/php.ini
#    regexp: "date.timezone ="
#    line: "date.timezone = UTC"
#  tags:
#    - config-files
#  notify: Restart Nginx
